services:
  librarycore:
    image: librarycore
    restart: on-failure
    build: ./library-core
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  libraryauth:
    image: libraryauth
    restart: on-failure
    build: ./library-auth
    ports:
      - 8081:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
