services:
  application:
    image: libraryapp
    restart: on-failure
    build: .
    ports:
    - 8081:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
