spring:
  datasource:
#    url: jdbc:postgresql://host.docker.internal:5432/library - на postgres на хосте
    url: jdbc:postgresql://postgres:5432/libraryauth
    username: postgres
    password: postgres
